version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: shopping_cart
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  db_shadow:
    image: mysql:8.0
    container_name: shopping_cart_shadow
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_SHADOW}
      MYSQL_DATABASE: ${MYSQL_DATABASE_SHADOW}
      MYSQL_USER: ${MYSQL_USER_SHADOW}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_SHADOW}
    volumes:
      - shadow_data:/var/lib/mysql

volumes:
  mysql_data:
  shadow_data:
